name: 更新KV的ips

on: [push]  # 你可以在 push 事件时触发此工作流程

jobs:
  update-data:
    runs-on: ubuntu-latest  # 使用最新的Ubuntu运行环境

    env:  # 在这里设置环境变量
      CF_DOMAIN: ${{ secrets.CF_DOMAIN }}
      CF_TOKEN: ${{ secrets.CF_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # 检出代码仓库

      - name: Set up environment
        run: |
          echo "CF_DOMAIN=${{ env.CF_DOMAIN }}" >> $GITHUB_ENV
          echo "CF_TOKEN=${{ env.CF_TOKEN }}" >> $GITHUB_ENV

      - name: Make script executable
        run: chmod +x./cfkv_ips.sh

      - name: Get files list
        run: |
          cd ip443
          files=$(ls HK1.txt KR1.txt JP1.txt SG1.txt US1.txt)  # 根据实际需要添加更多文件名
          echo "FILES=${files}" >> $GITHUB_ENV

      - name: Loop through files and run script
        run: |
          IFS=' ' read -ra FILE_ARRAY <<< "${{ env.FILES }}"
          for file in "${FILE_ARRAY[@]}"; do
           ./cfkv_ips.sh "${file}"
          done

